[build]
command = "npm run build"
publish = "build"
environment = { NODE_VERSION = "16", CI = "true" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[build.environment]
REACT_APP_SOLANA_NETWORK = "mainnet-beta"
REACT_APP_ENABLE_TESTNET = "false"
REACT_APP_ENABLE_DEVTOOLS = "false"

